#!/usr/bin/env python

from __future__ import print_function
import os
import sys
import argparse
import textwrap
import itertools
from pprint import pprint

def build_parser():
    parser = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--oauth_filename', default='~/.figshare-token',
        help='''Path to file storing oauth credentials''',
        type=os.path.expanduser)
    return parser

###############################################################################
# main entry point
###############################################################################

def main():
    parser = build_parser()
    args = parser.parse_args()
    try:
        action = ACTIONS[args.command]
    except KeyError:
        parser.print_help()
        parser.exit(1)
    action(figshare, args)

if __name__ == '__main__':
    main()
